qaCommandCenter/blueprints/auth.py
# -*- coding: utf-8 -*-

from faker import Faker
from flask import render_template, redirect, url_for, Blueprint, request, jsonify
from flask_babel import _
from flask_login import login_user, logout_user, login_required, current_user

from qaCommandCenter.extensions import db
from qaCommandCenter.models import User, Item

auth_bp = Blueprint('auth', __name__)
fake = Faker()


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('todo.app'))

    if request.method == 'POST':
        data = request.get_json()
        username = data['username']
        password = data['password']

        user = User.query.filter_by(username=username).first()

        if user is not None and user.validate_password(password):
            login_user(user)
            return jsonify(message=_('Login success.'))
        return jsonify(message=_('Invalid username or password.')), 400
    return render_template('_login.html')


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return jsonify(message=_('Logout success.'))


@auth_bp.route('/register')
def register():
    # generate a random account for demo use
    username = fake.user_name()
    # make sure the generated username was not in database
    while User.query.filter_by(username=username).first() is not None:
        username = fake.user_name()
    password = fake.word()
    user = User(username=username)
    user.set_password(password)
    db.session.add(user)
    db.session.commit()

    item = Item(body=_('Witness something truly majestic'), author=user)
    item2 = Item(body=_('Help a complete stranger'), author=user)
    item3 = Item(body=_('Drive a motorcycle on the Great Wall of China'), author=user)
    item4 = Item(body=_('Sit on the Great Egyptian Pyramids'), done=True, author=user)
    db.session.add_all([item, item2, item3, item4])
    db.session.commit()

    return jsonify(username=username, password=password, message=_('Generate success.'))

qaCommandCenter/blueprints/home.py
# -*- coding: utf-8 -*-

from flask import render_template, Blueprint, current_app, make_response, jsonify
from flask_babel import _
from flask_login import current_user
from qaCommandCenter.blueprints import CompanyFlow

from qaCommandCenter.extensions import db

home_bp = Blueprint('home', __name__)


@home_bp.route('/')
def index():
    return render_template('index.html')


@home_bp.route('/brokenlinks')
def brokenlinks():
    return render_template('resultsdash.html')

@home_bp.route('/companyflow')
def results():
    CompanyFlow.companyflow()
    return render_template('resultsdash.html')

@home_bp.route('/contractor')
def contractor():
    return render_template('resultsdash.html')

@home_bp.route('/managerflow')
def managerflow():
    return render_template('resultsdash.html')

@home_bp.route('/intro')
def intro():
    return render_template('_intro.html')


@home_bp.route('/set-locale/<locale>')
def set_locale(locale):
    if locale not in current_app.config['TODOISM_LOCALES']:
        return jsonify(message=_('Invalid locale.')), 404

    response = make_response(jsonify(message=_('Setting updated.')))
    if current_user.is_authenticated:
        current_user.locale = locale
        db.session.commit()
    else:
        response.set_cookie('locale', locale, max_age=60 * 60 * 24 * 30)
    return response

qaCommandCenter/blueprints/todo.py
# -*- coding: utf-8 -*-

from flask import render_template, request, Blueprint, jsonify
from flask_babel import _
from flask_login import current_user, login_required

from qaCommandCenter.extensions import db
from qaCommandCenter.models import Item

todo_bp = Blueprint('todo', __name__)


@todo_bp.route('/app')
@login_required
def app():
    all_count = Item.query.with_parent(current_user).count()
    active_count = Item.query.with_parent(current_user).filter_by(done=False).count()
    completed_count = Item.query.with_parent(current_user).filter_by(done=True).count()
    return render_template('_app.html', items=current_user.items,
                           all_count=all_count, active_count=active_count, completed_count=completed_count)


@todo_bp.route('/items/new', methods=['POST'])
@login_required
def new_item():
    data = request.get_json()
    if data is None or data['body'].strip() == '':
        return jsonify(message=_('Invalid item body.')), 400
    item = Item(body=data['body'], author=current_user._get_current_object())
    db.session.add(item)
    db.session.commit()
    return jsonify(html=render_template('_item.html', item=item), message='+1')


@todo_bp.route('/item/<int:item_id>/edit', methods=['PUT'])
@login_required
def edit_item(item_id):
    item = Item.query.get_or_404(item_id)
    if current_user != item.author:
        return jsonify(message=_('Permission denied.')), 403

    data = request.get_json()
    if data is None or data['body'].strip() == '':
        return jsonify(message=_('Invalid item body.')), 400
    item.body = data['body']
    db.session.commit()
    return jsonify(message=_('Item updated.'))


@todo_bp.route('/item/<int:item_id>/toggle', methods=['PATCH'])
@login_required
def toggle_item(item_id):
    item = Item.query.get_or_404(item_id)
    if current_user != item.author:
        return jsonify(message=_('Permission denied.')), 403

    item.done = not item.done
    db.session.commit()
    return jsonify(message=_('Item toggled.'))


@todo_bp.route('/item/<int:item_id>/delete', methods=['DELETE'])
@login_required
def delete_item(item_id):
    item = Item.query.get_or_404(item_id)
    if current_user != item.author:
        return jsonify(message=_('Permission denied.')), 403

    db.session.delete(item)
    db.session.commit()
    return jsonify(message=_('Item deleted.'))


@todo_bp.route('/item/clear', methods=['DELETE'])
@login_required
def clear_items():
    items = Item.query.with_parent(current_user).filter_by(done=True).all()
    for item in items:
        db.session.delete(item)
    db.session.commit()
    return jsonify(message=_('All clear!'))

qaCommandCenter/templates/_app.html
{% extends 'base.html' %}

{% block content %}
    <header class="row">
        <b>Note:</b>
        <p>To run test cases click on "Run" button. All test case results will be on the results summary page. To Access the results summary page click on the top left icon and select "Results Summary"</p>
    </header>
    <hr stye="margin-top:1%"></hr>
    <div class="row" style="align-content:center" id="dashboard">
        <div class="col l9 m12 s12">
            <ul class="tabs">
                <li class="tab col m4 s12">
                    <a class="blue-text button" id="all-item">
                        {{ _('Initiate Tests') }} <span class="grey-text small-text" id="all-count"></span>
                    </a>
                </li>
                <li class="tab col m4 s12">
                    <a class="blue-text button" id="active-item">
                        {{ _('Running Tests') }} <span class="grey-text small-text" id="active-count">
<!--                        {{ active_count }}-->
                    </span>
                    </a>
                </li>
                <li class="tab col m4 s12">
                    <a class="blue-text button" id="completed-item">
                        {{ _('Done') }} <span class="grey-text small-text"
                                              id="completed-count">{{ completed_count }}</span>
                    </a>
                </li>
            </ul>
        </div>
<!--        <div class="col l3 hide-on-med-and-down">-->
<!--            <a class="waves-effect waves-light btn red right" id="clear-btn">-->
<!--                <i class="material-icons left">clear_all</i>Clear-->
<!--            </a>-->
<!--        </div>-->
    </div>

    <div class="items">
        <div class="row item card-panel" data-body="Company Flow">
    <span class="item-body">
        Company Flow
    </span>

        <a class="waves-effect waves-light btn green right" href="/companyflow">Run Test</a>
</div>

<div class="row item card-panel "  data-body="Managers Flow">
    <span class="item-body">
        Managers Flow
    </span>
        <a class="waves-effect waves-light btn green right" href="/managerflow">Run Test</a>
</div>

<div class="row item card-panel hoverable"
      data-body="Contractor Flow">
    <span class="item-body">
        Contractor Flow
    </span>
        <a class="waves-effect waves-light btn blue green right" href="/contractor">Run Test</a>
</div>


<div class="row item card-panel "
      data-body="Contractor Flow">
    <span class="item-body">
        Check Broken Links
    </span>
        <a class="waves-effect waves-light btn green right" href="/brokenlinks">Run Test</a>
</div>
<!--        {% for item in items %}-->
<!--            {% include '_item.html' %}-->
<!--        {% endfor %}-->
    </div>
{% endblock %}

qaCommandCenter/templates/_intro.html
{% extends 'base.html' %}

{% block content %}
    <div class="center">
        <h2 class="teal-text text-lighten-2">Automation Command Center</h2>
        <h5 class="light">{{ _('We are Velocity Inc., we use ACC.') }}</h5>
        <div class="row center-block">
            <div class="fake-browser-ui hoverable card-panel">
                <div class="frame">
                    <span class="red"></span>
                    <span class="blue"></span>
                    <span class="orange"></span>
                </div>
                <img class="responsive-img" src="{{ url_for('static', filename=_('demo.png')) }}">
            </div>
        </div>
        <div class="row">
            <a href="#login" class="btn waves-effect waves-light red">{{ _('Get Started') }}</a>
        </div>
    </div>
{% endblock %}

qaCommandCenter/templates/_item.html
<div class="row item card-panel" data-body="Company Flow">
    <span class="item-body">
        Company Flow
    </span>

        <a class="waves-effect waves-light btn green right" href="#app">Run Test</a>
</div>

<div class="row item card-panel "  data-body="Managers Flow">
    <span class="item-body">
        Managers Flow
    </span>
        <a class="waves-effect waves-light btn green right" href="#app">Run Test</a>
</div>

<div class="row item card-panel hoverable"
      data-body="Contractor Flow">
    <span class="item-body">
        Contractor Flow
    </span>
        <a class="waves-effect waves-light btn blue green right" href="#app">Run Test</a>
</div>


<div class="row item card-panel "
      data-body="Contractor Flow">
    <span class="item-body">
        Check Broken Links
    </span>
        <a class="waves-effect waves-light btn green right" href="#app">Run Test</a>
</div>

qaCommandCenter/templates/_login.html
{% extends 'base.html' %}

{% block content %}
    <header class="center">
        <h4 class="blue-text">{{ _('Automation Command Center') }}</h4><br>
    </header>
    <div class="login-form">
        <input class="validate login-input" id="username-input" name="username" type="text" placeholder="Username"
               autofocus required>
        <input class="validate login-input" id="password-input" name="password" type="password" placeholder="Password"
               required>
        <span class="right">
            <a class="btn grey" id="register-btn">{{ _('Get a test account') }}</a>
            <a class="btn red" id="login-btn">{{ _('Login') }}</a>
        </span>
        <p><a class="blue-text link button left" id="toggle-password">{{ _('Toggle Password') }}</a></p>&nbsp;
    </div>
{% endblock %}

qaCommandCenter/templates/base.html
<nav class="black" role="navigation">
    <div class="nav-wrapper container">
        <a href="#intro" class="brand-logo">Automation Command Center</a>
        <a data-target="nav-mobile" class="sidenav-trigger button"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
            {% if current_user.is_authenticated %}
                <li>
                    <a class="waves-effect waves-light btn blue" href="#app">{{ current_user.username }}
<!--                        <span class="badge new" id="active-count-nav">{{ active_items }}</span>-->
                    </a>
                </li>
                <li>
                    <a class="waves-effect waves-light" id="logout-btn" data-href="{{ url_for('auth.logout') }}">
                        <i class="material-icons">power_settings_new</i>
                    </a>
                </li>
            {% else %}
                <li><a class="waves-effect waves-light btn red" href="#login">{{ _('Login') }}</a></li>
            {% endif %}
            <li>
                <a class="waves-effect waves-light dropdown-trigger" id="locale-dropdown-btn" data-target="locale-dropdown">
                    <i class="material-icons">language</i>
                </a>
            </li>
        </ul>
    </div>
</nav>

<ul id="nav-mobile" class="sidenav">
    {% if current_user.is_authenticated %}
<!--        <li><a class="waves-effect waves-light btn red clear-btn sidenav-close">Clear</a></li>-->
        <li><a class="waves-effect waves-light btn orange sidenav-close" id="app-btn"
               href="#app">{{ current_user.username }}</a>
        </li>
        <li><a class="waves-effect waves-light btn grey sidenav-close" id="logout-btn"
               data-href="{{ url_for('auth.logout') }}">{{ _('Logout') }}</a></li>
    {% else %}
        <li><a class="waves-effect waves-light btn red sidenav-close" href="#login">{{ _('Login') }}</a></li>
    {% endif %}
</ul>

<ul id="locale-dropdown" class="dropdown-content">
    <li><a class="lang-btn" data-href="{{ url_for('home.set_locale', locale='zh_Hans_CN') }}">Broken Links</a></li>
    <li><a class="lang-btn" href="http://100.26.188.231:3000/" target="_blank">Results Dashboard</a></li>
</ul>

<main>
    {% block content %}{% endblock %}
</main>
<footer class="center">
    <big> &copy; 2022 <a class="blue-text link" href="http://velocityinc.tech" title="Modified by Velocity Inc.">Velocity Inc. Technologies</a>

    </big>
</footer>

qaCommandCenter/templates/errors.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta charset="utf-8"/>
    <title>Error {{ code }} - Automation Command Center</title>
    <link href="{{ url_for('static', filename='css/materialize.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
</head>

<body>
<main>
    <header class="center">
        <h4 class="red-text">Command Center</h4>
    </header>
    <div class="row card-panel hoverable">
        <span class="col s10">
            <span class="active-item">{{ code }} - {{ info }}</span>
        </span>
        <span class="col s2">
            <a class="button right" href="{{ url_for('home.index') }}">{{ _('Back Home') }}</a>
        </span>
    </div>
</main>
</body>
</html>

qaCommandCenter/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta charset="utf-8"/>
    <title>Velocity | Automation Command Center</title>
    <link href="{{ url_for('static', filename='css/materialize.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/dashstyle.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/bootstrap/style.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon" rel="icon">
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    
</head>
<body>
<div id="main"></div>
<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/materialize.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/script.js') }}" type="text/javascript"></script>
<script type="text/javascript">
    var csrf_token = "{{ csrf_token() }}";
    var login_page_url = "{{ url_for('auth.login') }}";
    var app_page_url = "{{ url_for('todo.app') }}";
    var intro_page_url = "{{ url_for('home.intro') }}";
    var new_item_url = "{{ url_for('todo.new_item') }}";
    var clear_item_url = "{{ url_for('todo.clear_items') }}";
    var login_url = "{{ url_for('auth.login') }}";
    var register_url = "{{ url_for('auth.register') }}";
    var logout_url = "{{ url_for('auth.logout') }}";
    var default_error_message = "{{ _('Oops, something was wrong!') }}";
    var empty_body_error_message = "{{ _('Your automations were empty!') }}";
    var login_error_message = "{{ _('Empty username or password!') }}";
</script>
</body>
</html>

qaCommandCenter/templates/resultsdash.html
<!doctype html>
<html lang="en">
  <head>
  	<title>Table 05</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	
	<link rel="stylesheet" href="css/dashstyle.css">

	</head>
	<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center ">
					<h2 class="heading-section">Summary of Results
					</h2>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="table-wrap">
						<table class="table table-responsive-xl" id="#ex-table">
						  <thead>
						    <tr>
						    	<th>&nbsp;</th>
						    	<th>Test Case Name</th>
						      <th>Test Flow</th>
						      <th>Status</th>
						      <th>Environment</th>
						    </tr>
						  </thead>
						  <tbody>
						    <tr class="alert" role="alert">
						    	<td>
						    		<!-- <label class="checkbox-wrap checkbox-primary">
										  <input type="checkbox" checked>
										  <span class="checkmark"></span>
										</label> -->
						    	</td>
						      <td class="d-flex align-items-center">
						      	<div: url(images/person_1.jpg);"></div>
						      	<div class="pl-3 email">
						      		<span>markotto@email.com</span>
						      		<span>Added: 01/03/2020</span>
						      	</div>
						      </td>
						      <td>Managers Flow</td>
						      <td class="status"><span class="active">Passed</span></td>
						      <td>
						      	<p>Alpha</p>
				        	</td>
						    </tr>
							
						    
						  </tbody>
						</table>
						<script>
							config= {
								"admin":"require(firebase-admin)",
								"serviceAccount":require("https://console.cloud.google.com/iam-admin/serviceaccounts/details/116902753638229793085?authuser=0&project=qaresults-a35ee"),
								"credential": "admin.credential.cert(serviceAccount)",
								"databaseURL": "https://qaresults-a35ee-default-rtdb.firebaseio.com"
							
							}
							var firebase = config.initialize()
							var database = firebase.database();
							database.ref().once('value', function(snapshot){
								if(snapshot.exists()){
									var content = '';
									snapshot.forEach(function(data){
										var val = data.val();
										content +='<tr>';
										content += '<td>' + val.name + '</td>';
										content += '<td>' + val.price + '</td>';
										content += '<td>' + val.salePrice + '</td>';
						
										content += '</tr>';
									});
									$('#ex-table').append(content);
								}
							});
						</script>
						
					</div>
				</div>
			</div>
		</div>
	</section>

	<script src="js/jquery.min.js"></script>
  <script src="js/popper.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <script src="js/main.js"></script>

	</body>
</html>